parameters:
    sidus_eav_model.form.type.data.class: Sidus\EAVBootstrapBundle\Form\DataType
    sidus_eav_model.form.type.autocomplete_data_selector.class: Sidus\EAVBootstrapBundle\Form\AutocompleteDataSelectorType
    sidus_eav_model.form.type.sidus_bootstrap_collection.class: Sidus\EAVBootstrapBundle\Form\BootstrapCollectionType
    sidus_eav_model.form.type.sidus_date_picker.class: Sidus\EAVBootstrapBundle\Form\DatePickerType
    sidus_eav_model.form.type.sidus_datetime_picker.class: Sidus\EAVBootstrapBundle\Form\DateTimePickerType

services:
    sidus_eav_model.form.type.autocomplete_data_selector:
        class: %sidus_eav_model.form.type.autocomplete_data_selector.class%
        arguments: [%sidus_eav_model.entity.data.class%, @sidus_eav_model.doctrine.repository.data, @sidus_eav_model.family_configuration.handler]
        tags:
            - { name: form.type, alias: sidus_autocomplete_data_selector }

    sidus_eav_model.form.type.sidus_bootstrap_collection:
        class: %sidus_eav_model.form.type.sidus_bootstrap_collection.class%
        tags:
            - { name: form.type, alias: sidus_bootstrap_collection }

    sidus_eav_model.form.type.sidus_date_picker:
        class: %sidus_eav_model.form.type.sidus_date_picker.class%
        tags:
            - { name: form.type, alias: sidus_date_picker }

    sidus_eav_model.form.type.sidus_datetime_picker:
        class: %sidus_eav_model.form.type.sidus_datetime_picker.class%
        tags:
            - { name: form.type, alias: sidus_datetime_picker }
