parameters:
    sidus_eav_bootstrap.form.type.tabbed_data.class: Sidus\EAVBootstrapBundle\Form\Type\TabbedDataType
    sidus_eav_bootstrap.form.type.autocomplete_data_selector.class: Sidus\EAVBootstrapBundle\Form\Type\AutocompleteDataSelectorType
    sidus_eav_bootstrap.form.type.combo_data_selector.class: Sidus\EAVBootstrapBundle\Form\Type\ComboDataSelectorType
    sidus_eav_bootstrap.form.type.sidus_bootstrap_collection.class: Sidus\EAVBootstrapBundle\Form\Type\BootstrapCollectionType
    sidus_eav_bootstrap.form.type.sidus_date_picker.class: Sidus\EAVBootstrapBundle\Form\Type\DatePickerType
    sidus_eav_bootstrap.form.type.sidus_datetime_picker.class: Sidus\EAVBootstrapBundle\Form\Type\DateTimePickerType
    sidus_eav_bootstrap.form.type.sidus_wysiwyg.class: Sidus\EAVBootstrapBundle\Form\Type\WysiwygType
    sidus_eav_bootstrap.form.switch.type.class: Sidus\EAVBootstrapBundle\Form\Type\SwitchType
    mopa_bootstrap.form.type_extension.tabbed.class: Sidus\EAVBootstrapBundle\Form\Extension\TabbedFormTypeExtension

services:
    sidus_eav_bootstrap.form.type.tabbed_data:
        class: '%sidus_eav_bootstrap.form.type.tabbed_data.class%'
        parent: sidus_eav_model.form.type.data
        tags:
            - { name: form.type, alias: sidus_tabbed_data }

    sidus_eav_bootstrap.form.type.autocomplete_data_selector:
        class: '%sidus_eav_bootstrap.form.type.autocomplete_data_selector.class%'
        arguments: ['%sidus_eav_model.entity.data.class%', '@sidus_eav_model.doctrine.repository.data', '@sidus_eav_model.family_configuration.handler']
        tags:
            - { name: form.type, alias: sidus_autocomplete_data_selector }

    sidus_eav_bootstrap.form.type.combo_data_selector:
        class: '%sidus_eav_bootstrap.form.type.combo_data_selector.class%'
        arguments: ['@sidus_eav_model.family_configuration.handler']
        tags:
            - { name: form.type, alias: sidus_combo_data_selector }

    sidus_eav_bootstrap.form.type.sidus_bootstrap_collection:
        class: '%sidus_eav_bootstrap.form.type.sidus_bootstrap_collection.class%'
        tags:
            - { name: form.type, alias: sidus_bootstrap_collection }

    sidus_eav_bootstrap.form.type.sidus_date_picker:
        class: '%sidus_eav_bootstrap.form.type.sidus_date_picker.class%'
        tags:
            - { name: form.type, alias: sidus_date_picker }

    sidus_eav_bootstrap.form.type.sidus_datetime_picker:
        class: '%sidus_eav_bootstrap.form.type.sidus_datetime_picker.class%'
        tags:
            - { name: form.type, alias: sidus_datetime_picker }

    sidus_eav_bootstrap.form.type.sidus_wysiwyg:
        class: '%sidus_eav_bootstrap.form.type.sidus_wysiwyg.class%'
        tags:
            - { name: form.type, alias: sidus_wysiwyg }

    sidus_eav_bootstrap.form.switch.type:
        class: '%sidus_eav_bootstrap.form.switch.type.class%'
        tags:
            - { name: form.type, alias: sidus_switch }

    # Support for Symfony 2.8 : MopaBootstrapBundle doesn't use the alias for the tab type anymore
    sidus_eav_bootstrap.form.tab.type:
        parent: mopa_bootstrap.form.type.tab
        tags:
            - { name: form.type, alias: tab }
