parameters:
    sidus_eav_bootstrap.twig.extension.class: Sidus\EAVBootstrapBundle\Twig\SidusTwigExtension

services:
    sidus_eav_bootstrap.twig.extension:
        class: %sidus_eav_bootstrap.twig.extension.class%
        arguments: [@sidus_eav_model.family_configuration.handler, @translator]
        tags:
            - { name: 'twig.extension' }

